[package]
name = "schema_parser"
version = "0.1.0"
authors = ["Dominik Boehi <dominik.boehi@gmail.com>", "Noah Huesser <yatekii@yatekii.ch>"]

[lib]
name = "schema_parser"
path = "src/lib.rs"

[[bin]]
name = "schema_renderer"
path = "src/main.rs"


[dependencies]
nom = "*"
gfx = "*"
gfx_window_glutin = "*"
gfx_device_gl = "*"
gfx_glyph = "*"
glutin = "*"

lyon = "*"
euclid = "^0.15.1"

lyon_tessellation = "*"
lyon_path = "*"
lyon_core = "*"

log = "*"
env_logger = "*"